### ISSUE TITLE
Support for VRV.co?

### ISSUE THREAD

**Issue by katzenbaer** [amarcu5/PiPer#10]
Could you add support for vrv.co? It would be much appreciated. :)

**Comment by amarcu5** [comment]
Thanks for the feature request. VRV (with experimental caption) is now supported on the develop branch b54770bd755a4d9de2f4c273ae7a2cec9705787a

**Comment by katzenbaer** [comment]
Hey @amarcu5 , I'm having an issue with the develop build where the captions don't update if the VRV.co tab is not focused.

# Reproduction Steps
1. Open a video on VRV.co.
2. Go into PIP.
3. Switch to another tab on Safari.
4. Notice that the captions are frozen/do not appear 
5. Focus the VRV.co tab.
6. Notice that the captions work properly again.

**Comment by amarcu5** [comment]
Appreciate the detailed reproduction steps. Now fixed on the develop branch 4ebaab2368fe15437a5b700ebc2eca1ebca333b1

**Comment by katzenbaer** [comment]
Hi @amarcu5, are the binaries always up to date at https://rawgit.com/amarcu5/PiPer/develop/out/PiPer.safariextz? I removed my existing extension and installed the one available at that URL, but I am still having the issue.

**Comment by amarcu5** [comment]
Strange, the binaries are always up-to-date and it works fine for me. I've noticed Safari is a little aggressive at caching old versions of an extension; I suggest uninstalling the extension from settings, quitting safari, and then re-opening Safari/installing the new version.

**Comment by katzenbaer** [comment]
Thanks for the update. Your observation was correct, and the issue has been fixed after a restart and reinstall of the extension.
