### ISSUE TITLE
Plex PiP broken

### ISSUE THREAD

**Issue by mcreston** [amarcu5/PiPer#15]
just today the PiP icon is no longer visible in the player window in plex on safari.  see attached screenshot/differences to what it used to look like yesterday.  

![screen shot 2017-08-04 at 11 56 24 am](https://user-images.githubusercontent.com/30734497/28983483-d706ee40-790e-11e7-8fc5-47a18d0b7ee9.jpg)
![screen shot 2017-08-04 at 11 56 44 am](https://user-images.githubusercontent.com/30734497/28983482-d6f7526e-790e-11e7-87ea-a682f8e2b0c7.jpg)

**Comment by amarcu5** [comment]
Thanks for the bug report. This is now fixed on the develop branch and I've also added experimental support for closed captions. 446b106b46cb6d725093a0a7773855264969b01c

**Comment by mcreston** [comment]
huzzah.  thanks


Blake Marvin
214.725.0115
www.blakemarvin.com <http://blakemarvin.com/>
blakemarvin@gmail.com <mailto:blakemarvin@gmail.com>
