### ISSUE TITLE
netflix is now broken/missing PiP icon in player bar

### ISSUE THREAD

**Issue by mcreston** [amarcu5/PiPer#19]
plex is fixed with the new version but netflix is broken.  this is with the version that is posted on the safari extensions gallery (0.2.1)

b

**Comment by amarcu5** [comment]
Strange, works fine for me and I'm not aware of any recent UI changes. 

Are you enrolled in Netflix's test participation? If so, you can try [opting out](http://showgoers.tv/test_opt_out.html)

**Comment by mcreston** [comment]
i think that did the trick.  thanks
