### ISSUE TITLE
JW Player

### ISSUE THREAD

**Issue by jshmllr** [amarcu5/PiPer#2]
Could you provide the ability to do PIP for the JW Player? 
[JW Player](https://www.jwplayer.com/learn-more/)

**Comment by amarcu5** [comment]
Supporting **individual** sites that use JW Player is straightforward. However supporting **all** sites using JW Player is complicated without compromising privacy and performance.
 
Was there a specific site you wanted support for?

**Comment by amarcu5** [comment]
I'll be closing this now - feel free to create a new issue if there is a specific site you want support for.

**Comment by iBobik** [comment]
How about to add generic helper function for JW player, so supporting individual sites will be more straightforward and code-saving?
