### ISSUE TITLE
Button no longer appearing on Netflix

### ISSUE THREAD

**Issue by j4y4r1987** [amarcu5/PiPer#24]
Running latest version, but also tried previous 2 - Netflix must have changed something on their end.

**Comment by amarcu5** [comment]
Works fine for me. Could be a duplicate of issue #19 

Are you enrolled in Netflix's test participation? If so, you can try [opting out](http://showgoers.tv/test_opt_out.html)

**Comment by j4y4r1987** [comment]
You're right. I'm so sorry! It's working just fine. Thank you!
