### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by sohansubhash** [amarcu5/PiPer#29]
It would be great if you could add a keyboard shortcut. Maybe ⌘+ ⌥ + P (Command + Option + P)

**Comment by amarcu5** [comment]
Great idea! Would love to support this but [this Safari bug](https://bugs.webkit.org/show_bug.cgi?id=178409) needs to be fixed first.

**Comment by noahmaranesi** [comment]
Any update on this?

**Comment by gershik** [comment]
Bump
