### ISSUE TITLE
Button no longer shows on Twitch

### ISSUE THREAD

**Issue by Wolster** [amarcu5/PiPer#36]
Hey, thanks for this great extension with proper permissions!

It's seems the extension no longer works on twitch - the button simply does not show. I'm on Safari 11.0.1 (13604.3.5). It works fine on the other sites I've tested with. I am unsure if this has happened since the macOS beta was updated or Twitch changed something on their end, unfortunately I don't have an other Safari version to test with.

Edit: Seems to only happen when the site is in "beta" mode.

**Comment by amarcu5** [comment]
Thanks for the report. This is now fixed on the develop branch along with support for closed captions. 787787405eff0596d81d875830615f8218c7195c
