### ISSUE TITLE
PiP button position on Twitch

### ISSUE THREAD

**Issue by choco** [amarcu5/PiPer#40]
Hello, with latest update the PiP button is the third last in the player, while it was the second to last in previous version. Would it be possible to change that back? That way it would be consistent with Youtube, that has Theater, PiP, Fullscreen.

<img width="182" alt="screen shot 2017-11-11 at 18 21 18" src="https://user-images.githubusercontent.com/85527/32691831-1a20e936-c70e-11e7-987d-ef52d336d86c.png">

**Comment by amarcu5** [comment]
Thanks for the bug report. This is now fixed on the develop branch a53519f910fe554d9a7783015b1a3cc3b2c4216a
