### ISSUE TITLE
New sites

### ISSUE THREAD

**Issue by rk492** [amarcu5/PiPer#42]
Can you add support for Amazon Prime Video, TVE and HBO?

**Comment by amarcu5** [comment]
Thanks for the feature request. Amazon Prime Video is already supported, TVE should be easy to add, HBO is a no go until they move away from flash.

**Comment by rk492** [comment]
Hi! Thanks for your quick answer! Sorry, I wanted to say that Amazon doesn't work fine. 
<img width="1280" alt="captura de pantalla 2017-11-18 a las 17 21 45" src="https://user-images.githubusercontent.com/31762467/32982441-4113363a-cc85-11e7-8f88-2fe2daf70e8d.png">

**Comment by kurzweilbarr** [comment]
@amarcu5 What about supporting mlb.com live feeds now that they have moved away from the flash player?

**Comment by akhats** [comment]
can you add support for pbs.org and pbs.org/nova

**Comment by amarcu5** [comment]
MLB (thanks @kurzweilbarr), PBS, and Amazon Prime Video are now supported.

HBO is still using Flash and will not be supported. TVE is on my list to add support for but is complicated by using many different designs of video player.

I'll be closing this issue now and would appreciate support for any new sites be made as separate issues, thanks!

**Comment by rk492** [comment]
Hi! Thanks for your support! The problem with Amazon Prime is the same, it don't show properly like in the photo
