### ISSUE TITLE
Youtube stops buffering when not on screen

### ISSUE THREAD

**Issue by krokofant** [amarcu5/PiPer#44]
PiP mode works but if the Safari windows is on another screen then it doesn't seem to download more of the video. Going back to the screen with youtube makes it work a small amount of time.

Using the latest master

**Comment by amarcu5** [comment]
This has become my white whale and is a very tricky bug to pin down as it occurs intermittently. However I think I may have finally fixed it and have a messy patch that seems to work but would love others to try, any takers?

**Comment by krokofant** [comment]
@amarcu5 Push it and I'll try this week

**Comment by amarcu5** [comment]
@krokofant Done, check out the new [develop-youtubebufferingfix](https://github.com/amarcu5/PiPer/tree/develop-youtubebufferingfix) branch

**Comment by amarcu5** [comment]
@krokofant initial commit was bugged but is fixed now, make sure you test the latest version!

**Comment by krokofant** [comment]
@amarcu5 
Sorry for the late response, I was away on vacation. It seems to work great even with Safari minimised and on another screen.

**Comment by amarcu5** [comment]
@krokofant Glad to hear it, I'll clean up the code and push a new version this week.

With this bug finally squashed I can move onto better things like modularising the codebase and Chrome support!

**Comment by amarcu5** [comment]
This is now fixed on the develop branch a021a402595dc03b914917cb2ac6d403a659dc86
