### ISSUE TITLE
Does not work at all in Safari 11.0.2

### ISSUE THREAD

**Issue by julian-weinert** [amarcu5/PiPer#45]
The extension only shows the following error in the console:

    [Error] TypeError: a.webkitSetPresentationMode is not a function. (In 'a.webkitSetPresentationMode("picture-in-picture"==a.webkitPresentationMode?"inline":"picture-in-picture")', 'a.webkitSetPresentationMode' is undefined)
	(anonymous function) (main.js:3:189)

**Comment by amarcu5** [comment]
Apologies for the delayed response, I presume you're using macOS 10.11 (El Capitan). Picture in Picture requires macOS 10.12 (Sierra) onwards.

Unfortunately there's no way to restrict extensions to specific versions of macOS but having it totally break is a poor user experience. I'll leave this open until I can come up with a better solution.

**Comment by amarcu5** [comment]
Addendum: This will be fixed with the move to the Mac App Store as I can restrict installation of PiPer to macOS 10.12 onwards.
