### ISSUE TITLE
PiP Button on the left of Fullscreen

### ISSUE THREAD

**Issue by MentalGear** [amarcu5/PiPer#5]
Hi man,
Just wanted to say first that your extension is absolutely awesome !
However, wouldn't it make more sense to have the PiP button second on the left to the Fullscreen button. For that the fullscreen button would still be at the outmost right, as the user normally expects it to be.

**Comment by amarcu5** [comment]
Thanks, I've debated button placement before and have favoured style/ease of coding over consistency. For YouTube moving the button is a one liner so I'll change this shortly. Not all sites are this straightforward - I'm curious if others feel strongly about this?

**Comment by amarcu5** [comment]
Changed for YouTube, Amazon video, and Twitch on the develop branch 295d3cd4253dce8c61fa922f97c3c20d2cb403ff
