### ISSUE TITLE
Netflix not working?

### ISSUE THREAD

**Issue by rochakagrawal** [amarcu5/PiPer#52]
The extension works fine on youtube.. but I am unable to see the PIP icon when playing Netflix?

Do I need to do something extra to get the icon to show up?

thanks

**Comment by amarcu5** [comment]
Netflix works fine for me, its possible changes haven't rolled out to all users yet. Perhaps you're enrolled in test participation? If so, you can try [opting out](https://www.netflix.com/DoNotTest)

**Comment by amarcu5** [comment]
Please see issue #55
