### ISSUE TITLE
Youtube "Up Next" thumbnails blank

### ISSUE THREAD

**Issue by negitek** [amarcu5/PiPer#53]
<img width="489" alt="screen shot 2018-06-25 at 7 11 33 pm" src="https://user-images.githubusercontent.com/26349128/41886661-5bf4ab18-7938-11e8-8194-e271587d8a13.png">

**Comment by amarcu5** [comment]
I'm not certain this is related to PiPer and have not encountered this myself. Are you able to reproduce this?

The new release coming next week has quite a few YouTube related changes and I'd love to hear whether this still remains an issue.

**Comment by negitek** [comment]
Thanks for the reply, I think you're right.  My adblocker might be reason why I'm having this issue.  Should of tested it before posting.
