### ISSUE TITLE
No PiP button on new Netflix Player UI

### ISSUE THREAD

**Issue by ximi** [amarcu5/PiPer#55]
Today I started seeing a new Netflix Web Player UI, I'm not sure if this is a general release or if I'm in a beta program of some kind.

The new UI doesn't show the PiP button. I've attached a screenshot below:
<img width="1840" alt="New Netflix Web Player UI" src="https://user-images.githubusercontent.com/738693/42863746-c32d13fc-8a6c-11e8-968a-52300a7bcc34.png">

**Comment by amarcu5** [comment]
Thanks for the bug report and pull request. I've not been affected by the new UI, can you please check you're not enrolled in [Netflix's test participation](https://www.netflix.com/donottest)?

**Comment by matt3224** [comment]
I have this too

**Comment by ximi** [comment]
I was indeed in the test program. Deactivating that brings back the old UI, though I presume the new UI might become a general release at some point in the future

**Comment by amarcu5** [comment]
@ximi no worries, I'll be happy to reopen this issue and accept your pull request when that day comes
