### ISSUE TITLE
Video native control show up after quitting PiP mode

### ISSUE THREAD

**Issue by choco** [amarcu5/PiPer#6]
As the title says, once I get out of PiP mode, the native controls of the video elements become visible (the ones that you would see if the player doesn't provide custom ones). Would it be possible to keep them hidden?

EDIT:
Added a screenshot that shows what I mean
<img width="1680" alt="screen shot 2017-05-03 at 01 13 35" src="https://cloud.githubusercontent.com/assets/85527/25643082/e1a3557e-2f9d-11e7-8176-5c81bb062a46.png">

**Comment by amarcu5** [comment]
Appreciate the report, this is actually a bug in the latest Safari Technology Preview. In case it doesn't get fixed before public release I've come up with a quick workaround: 

```diff
     const presentationMode = 'inline' === video.webkitPresentationMode ? 'picture-in-picture' : 'inline';
     video.webkitSetPresentationMode(presentationMode);
+    
+    video.controls = true;
+    video.controls = false;
   });
 
   const referenceNode = currentResource.buttonInsertBefore ? currentResource.buttonInsertBefore(parent) : null;
```

**Comment by amarcu5** [comment]
Bug appears to be fixed in the latest release (32) of the Safari Technology Preview
