### ISSUE TITLE
[chrome extension] PiPer icon in plex.tv is big and shows when hidden

### ISSUE THREAD

**Issue by fxjkhr** [amarcu5/PiPer#64]
Using version 1.0.0 from the chrome store.

screenshots of issue 

when menu controls are shown:
![image](https://user-images.githubusercontent.com/780260/49343850-d0f87700-f624-11e8-86a2-0ce72e1f9ced.png)

and when menu controls are hidden:
![image](https://user-images.githubusercontent.com/780260/49343892-22a10180-f625-11e8-88b0-f1a57ab79851.png)

Also, is it possible to use PiPer when visiting plex through a different address (like an IP address)

**Comment by amarcu5** [comment]
Thanks for the bug report. The button size now shows correctly using Chrome on the develop branch with anticipated release sometime next week e8a20524f0602c30fda31d85a7fe81bd7d59ca0a

Regarding Plex support on arbitrary IP addresses', this is not possible at present as there is no perfect solution without compromising performance. Things I've considered:
1) Quick and dirty - add aliases' for Plex to additionally work on localhost, 127.0.0.1, and ::1
2) More flexible but complicated - Add a customisable IP address or range of addresses' in PiPer's settings that Plex will work on

The first option is an easy change that could be done in a few minutes so I'm interested to know whether this would cover your use case. As always I'm open to suggestions if anyone can think of something better!

**Comment by amarcu5** [comment]
PiPer now support's the Plex Web App accessed locally through your Plex Media Server (i.e. using an IP address) on the develop branch aae3e5cd2aaad9c7be3f28be00d3f3819ef33f50
