### ISSUE TITLE
Hulu doesn't work with new web redesign 

### ISSUE THREAD

**Issue by robchron** [amarcu5/PiPer#65]
With Hulu's site overhaul, piper no longer works in safari :( 

I can get it to work in chrome by using their built in minimize thing, then right clicking and choosing picture in picture.

**Comment by amarcu5** [comment]
Thanks for the bug report. This is now fixed on the develop branch, expect a release sometime next week 0eaa689cf121ee48e7d8e22aa44fed72c5b0038b
