### ISSUE TITLE
Netflix PiPer button does not show up (in new UI?)

### ISSUE THREAD

**Issue by andrewngai** [amarcu5/PiPer#67]
Netflix PiPer button does not show up maybe in the updated web UI.

**Comment by amarcu5** [comment]
Thanks for the bug report, Netflix seems to work fine for me:

1) Can you please confirm you are using the latest version of PiPer from the [Mac App Store](https://itunes.apple.com/app/id1421915518?mt=12&ls=1) or [Chrome Web Store](https://chrome.google.com/webstore/detail/piper/jbjleapidaddpbncgofepljddfeoghkc) (note that the Safari Extension Gallery version is outdated!)
2) Can you please check you're not enrolled in Netflix's [test participation](https://www.netflix.com/donottest)?

**Comment by andrewngai** [comment]
> Thanks for the bug report, Netflix seems to work fine for me:
> 
> 1. Can you please confirm you are using the latest version of PiPer from the [Mac App Store](https://itunes.apple.com/app/id1421915518?mt=12&ls=1) or [Chrome Web Store](https://chrome.google.com/webstore/detail/piper/jbjleapidaddpbncgofepljddfeoghkc) (note that the Safari Extension Gallery version is outdated!)
> 2. Can you please check you're not enrolled in Netflix's [test participation](https://www.netflix.com/donottest)?

ahhh, my bad. I downloaded from the Safari Extension Gallery. Problem solved
