### ISSUE TITLE
Security Warning

### ISSUE THREAD

**Issue by MentalGear** [amarcu5/PiPer#7]
When I opened safari today, it told me the PiPer extension has been updated. However, as it now requires additional permissions, which could lead to security risks, the extension has been automatically deactivated.

Has there been some significant change since the last version that would trigger such an action from safari ? Maybe you might try to reverse it then, or run into the risk of have the extension automatically deactivated for a big chunk of users.

**Comment by Fofer** [comment]
I got the same alert, and was equally concerned.  I'd love some clarification on this from @amarcu5.
 
My hope is that compatibility with some new website(s) was added, and that's all. Since each website is listed in the permissions list, I'm thinking any addition(s) would push that alert...

**Comment by amarcu5** [comment]
@Fofer is correct - this is expected behaviour after an update that supports new sites. PiPer only asks for permission to access the sites it **needs** rather than **all** sites. Adding a new site requires new permissions and manual reactivation. I appreciate this is not a great user experience but the price you pay for better security. Given all the concern, I don't think this is the right choice and will ask permission to **all** sites next update so that this does not become an ongoing issue.

**Comment by Fofer** [comment]
Great, thanks @amarcu5.  Is there a version history anywhere so we can see what's added with each update?  Just out of curiosity.

**Comment by MentalGear** [comment]
Ah, okay. Though I'm wondering why I didn't get that security warning before when the extension initially.

**Comment by MentalGear** [comment]
Just wanted to add that I find it definitely better if the permission set is not global, but limited to the websites that the user can use PiP. It only needs a small hint UI wise from the app to not be confusing. :)

**Comment by amarcu5** [comment]
@Fofer sure thing: https://github.com/amarcu5/PiPer/releases

@MentalGear downloading an extension from the gallery doesn't prompt for permissions although it probably should. Thanks, before making any changes I'll see if I can come up with a better solution - open to suggestions!

**Comment by elfey** [comment]
This happened again and was a bit alarming to me. Maybe the better solution is to explain via the application or a prompt, or the description, what the additional permissions were and to reassure the user that nothing sketchy is going on.
