### ISSUE TITLE
Doesn't work with Fubo.tv

### ISSUE THREAD

**Issue by macsmister** [amarcu5/PiPer#70]
Is there any way you could test the plugin on Fubo.tv? No PiP icon appears on the streams... on macOS Safari version 12.1 (14607.1.22).

**Comment by amarcu5** [comment]
Thanks for the feature request, FuboTV is now supported (5ffd3fd1404c8d09e1e121263e58d7c4f997c2be) and should be available in the 1.0.2 release sometime next week

**Comment by macsmister** [comment]
Fantastic news! Looking forward to checking it out when 1.0.2 drops. Grand donation incoming also.

**Comment by amarcu5** [comment]
1.0.2 released, apologies for the delay!
