### ISSUE TITLE
Button on Hulu does nothing [chrome]

### ISSUE THREAD

**Issue by discodan** [amarcu5/PiPer#73]
This is an amazing extension and thank you for your work on it.

I've tested it on Amazon and Netflix, and it works fine. However, when I push the button on Hulu, it does nothing. 

I do see an uncaught DOMException in the console, but I can't really make out what is happening.

**Comment by amarcu5** [comment]
Thanks for the bug report. This is now fixed on the develop branch and I'll try to release a hotfix soon as Hulu is quite popular! 3b66f11732a6caba754d4f111cc51f657098616c

**Comment by discodan** [comment]
When were you planning on deploying this?

**Comment by amarcu5** [comment]
So sorry, life got the better of me, expect a release next week.
