### ISSUE TITLE
Hulu not working in Chrome

### ISSUE THREAD

**Issue by markmals** [amarcu5/PiPer#76]
Pressing the PiP button in Chrome doesn't work for me anymore. It appears that Hulu has added the `disablepictureinpicture` attribute to their `<video>` tag (but only in Chrome, as it doesn't appear in Safari, which is odd 🤔). See attachment for details.
![Hulu  video](https://user-images.githubusercontent.com/39869007/56952211-667a3300-6aff-11e9-96f6-65b2fe62addf.png)

**Comment by amarcu5** [comment]
Thanks for the bug report, please see issue #73. This is fixed on the latest release which should be out next week.
