### ISSUE TITLE
Czech TV support

### ISSUE THREAD

**Issue by tomasokol** [amarcu5/PiPer#77]
Hi, please try adding support to ceskatelevize.cz, for live broadcast (example: ct24.ceskatelevize.cz/#live) as well as non-live videos. 
Thx

**Comment by amarcu5** [comment]
Thanks for the feature request. Czech TV is now supported (e94aaa2e36fa74c78079172d34c38bd60d5a86f4) and will be available in the 1.0.3 release planned for next week.
