### ISSUE TITLE
Crunchyroll support

### ISSUE THREAD

**Issue by dar-irl** [amarcu5/PiPer#79]
Surprised this isn't already implemented, but could Crunchyroll be supported?

Also, would it be possible to have a toolbar button like PiPifier does so that, in the event that a website isn't explicitly supported, we'd still have some way to use PiPer?

**Comment by amarcu5** [comment]
Thanks for the feature request. Initial Crunchyroll support has now been added d2e6406184065e5fc24849a5baca45ab42831cdb. Currently working on supporting captions but not sure if it will make it into the next release.

Adding a toolbar button is definitely on the roadmap which should address websites that aren't explicitly supported. My reluctance to date has been that the approach used by PiPifier requires you first interact with the video player before the button can work. I find this to be a poor user experience but have yet to find a workaround.
