### ISSUE TITLE
Udemy player becomes bugged after installing PiPer

### ISSUE THREAD

**Issue by LuanAraldi** [amarcu5/PiPer#82]
After installing the chrome extension of PiPer, and opening an Udemy video, its video player button such as play, pause and fullscreen goes to the top of the video and some buttons become inaccessible.

Versions
Google Chrome : 76.0.3809.100
OS: Linux arch 5.2.8-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 9 21:36:07 UTC 2019 x86_64 GNU/Linux

**Comment by amarcu5** [comment]
Thanks for the bug report. This is now fixed on the develop branch, expect a release sometime next week d8b3cfdc1665748953cbf2c7dcdf5cc5d493c574
