### ISSUE TITLE
Twitch Issue

### ISSUE THREAD

**Issue by ivanwright** [amarcu5/PiPer#87]
Many thanks for Piper! It's an indispensable extension for me.

Twitch's ongoing UI changes seem to have affected Piper's support for the site. I no longer get the picture-in-picture button when viewing a stream normally. 

FWIW, invoking Twitch's pop out player from a stream's gear button does result in the PiP button loading for the stream.

**Comment by troymaclure** [comment]
Same for me. The Picture In Picture doesn't appear on the video layout.

> FWIW, invoking Twitch's pop out player from a stream's gear button does result in the PiP button loading for the stream.

Thanks for the tip.

**Comment by amarcu5** [comment]
Thanks for the bug report. Apologies for taking so long - this is now fixed on the develop branch and should be released within a week ccc4ec31a7df7164500091f53177102249aef12f
