### ISSUE TITLE
NBA.com support

### ISSUE THREAD

**Issue by semihyagli** [amarcu5/PiPer#9]
Extension is awesome. I dont know if there is any technical difficulties for this, but could you please add NBA.com support (or adobe flash player support in general) as well.

Thanks

**Comment by amarcu5** [comment]
Thanks,

NBA.com videos support Picture in Picture mode natively, so I figure you mean NBA League Pass? I don't have access to a subscription myself so won't be able to add support but would gladly accept a contribution from someone else.

If it uses flash, as you hinted at, then it's a no go - supporting flash player videos is tough if not impossible!

**Comment by semihyagli** [comment]
Oh, you see, if you allow flashplayer on nba.com, then picture in picture is not supported, but if you disable it, apple uses its native video player on nba.com which supports picture in picture. Now, I have disabled flashplayer on nba.com and my problem is resolved thanks!

**Comment by amarcu5** [comment]
Haha, glad I could help!
